//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDesignPattern
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieReturned
    {
        public int ReturnID { get; set; }
        public string MovieTitle { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> TotalRent { get; set; }
    }
}
